<a href="https://colab.research.google.com/github/Henao/python-samples/blob/master/HenaoNotebookPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [79]:
pd.read_csv('https://github.com/JuanPabloMF/datasets-platzi-course/blob/master/datasets/peliculas.csv?raw=true')

movie_title  ...        gross
0                                               Avatar   ...  760505847.0
1             Pirates of the Caribbean: At World's End   ...  309404152.0
2                                              Spectre   ...  200074175.0
3                                The Dark Knight Rises   ...  448130642.0
4     Star Wars: Episode VII - The Force Awakens    ...  ...          NaN
...                                                 ...  ...          ...
5038                           Signed Sealed Delivered   ...          NaN
5039                         The Following               ...          NaN
5040                              A Plague So Pleasant   ...          NaN
5041                                  Shanghai Calling   ...      10443.0
5042                                 My Date with Drew   ...      85222.0

[5043 rows x 19 columns]

In [80]:
a1 = np.array([1,2,3,4])
a1
type(a1)

numpy.ndarray

In [81]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a3 = np.zeros((2,3))
a4 = np.ones((2,3))

In [83]:
from IPython.display import display
display(a3);display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

**np.linspace(a, b, n)** es una función que permite crear arrays de una dimensión, de largo n y que contiene puntos entre ay b distanciados de forma regular. **La distancia entre cada punto será de (b-a)/(n-1)**

In [84]:
a5 = np.linspace(1,5,10)
display(a5)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [85]:
a3.dtype

dtype('float64')

**Dimensión de un Array**

Array de dimensión 1, es un vector por eso no aparece la segunda coordenada

In [86]:
a1.shape

(4,)

Array de 2 filas y tres columnas, matriz

In [87]:
a3.shape

(2, 3)

Si lleva doble [[]] se considera una matriz

In [88]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [89]:
np.array_equal(a1D,a2D)

False

**Reshaping**

In [90]:
new_dims = (1, a1D.shape[0])
a = a1D.reshape(new_dims)

In [91]:
a

array([[1, 2, 3]])

In [92]:
(1, a1D.shape[0])


(1, 3)

In [32]:
np.array_equal(a,a2D)

True

**Accesos a Elementos y Slicing**


In [34]:
a = np.array([[1,0,3], [4,3,5], [6, 10, -1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

El primer argumento es la linea y el segundo la columna. los arrays estan indexados desde cero

In [37]:
a[0,1]

0

In [93]:
a = np.arange(10)
b = np.eye(3)
display(a); display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
a[5:]

array([5, 6, 7, 8, 9])

In [52]:
b[0:2,0]

array([1., 0.])

In [95]:
b[1,0:3]

array([0., 1., 0.])

In [ ]:
b[2:,:]

array([[0., 0., 1.]])

In [ ]:
z = np.arange(4)
print('z      =', z)
print('z + 5 =', z + 5)
print('z - 5 =', z - 5)
print('z * 2 =', z * 2)
print('z / 2 =', z / 2)
print('z // 2 =', z // 2)
print('-z     =', -z)
print('z ** 2 =', z ** 2)
print('z % 2 =', z % 2)

z      = [0 1 2 3]
z + 5 = [5 6 7 8]
z - 5 = [-5 -4 -3 -2]
z * 2 = [0 2 4 6]
z / 2 = [0.  0.5 1.  1.5]
z // 2 = [0 0 1 1]
-z     = [ 0 -1 -2 -3]
z ** 2 = [0 1 4 9]
z % 2 = [0 1 0 1]


In [96]:
z+z

array([0, 2, 4, 6])

In [102]:
x = np.arange(4)
b = np.arange(1,5)

display(np.exp(x))  #exponencial
display(np.log(b))  #logaritmo
display(np.sqrt(x))  #raiz cuadrada
display(np.greater(b,x)) #superior o igual punto a punto


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([ True,  True,  True,  True])

In [101]:
display(x); display(b)

array([0, 1, 2, 3])

array([1, 2, 3, 4])

In [103]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i= 0
for el in a:
  b[i] = el +el
  i+=1


1 loop, best of 3: 295 ms per loop


In [104]:
%%timeit
a+a

The slowest run took 229.15 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 560 ns per loop


**Estadistica y aleatoriedad**

In [105]:
#estadistica
a = np.arange(10)

display(np.mean(a))  #promedio
display(np.median(a)) # Mediana


4.5

4.5

In [106]:
np.percentile(a,40)  #percentil

3.6

In [108]:
np.random.random(10) #Aleatoreidad

array([0.6113328 , 0.41659234, 0.85154157, 0.36025101, 0.23776954,
       0.05073163, 0.31220093, 0.53071072, 0.43843654, 0.73201887])